### ISSUE TITLE
correct presence / user thing

### ISSUE THREAD

**Issue by afxx44** [zfex77/simplechat#2]
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="//cdn.pubnub.com/pubnub.min.js"></script>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="alert alert-info">You are <strong id="whoami"></strong></div>
      <div class="panel panel-default">
        <div class="panel-heading">Online Users</div>
        <div class="list-group" id="online-users"></div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">Live Chat</div>
        <ul class="list-group" id="chat-output"></ul>
        <div class="panel-body">
          <form id="chat">
            <div class="input-group">
              <input type="text" class="form-control" id="chat-input" />
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default">Send Message</button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
// generate a random username
var randomName = function() {
  
  var animals = ['pigeon', 'seagull', 'bat', 'owl', 'sparrows', 'robin', 'bluebird', 'cardinal', 'hawk', 'fish', 'shrimp', 'frog', 'whale', 'shark', 'eel', 'seal', 'lobster', 'octopus', 'mole', 'shrew', 'rabbit', 'chipmunk', 'armadillo', 'dog', 'cat', 'lynx', 'mouse', 'lion', 'moose', 'horse', 'deer', 'raccoon', 'zebra', 'goat', 'cow', 'pig', 'tiger', 'wolf', 'pony', 'antelope', 'buffalo', 'camel', 'donkey', 'elk', 'fox', 'monkey', 'gazelle', 'impala', 'jaguar', 'leopard', 'lemur', 'yak', 'elephant', 'giraffe', 'hippopotamus', 'rhinoceros', 'grizzlybear']

  var colors = ['silver', 'gray', 'black', 'red', 'maroon', 'olive', 'lime', 'green', 'teal', 'blue', 'navy', 'fuchsia', 'purple'];

  return colors[Math.floor(Math.random() * colors.length)] + '_' + animals[Math.floor(Math.random() * animals.length)];
  
}

var me = randomName();
$('#whoami').text(me);

var $input = $('#chat-input');
var $output = $('#chat-output');

var pubnub = PUBNUB.init({
  publish_key: 'demo',
  subscribe_key: 'demo',
  uuid: me
});

var channel = 'memewarz-lobby-demo-5';

$('#chat').submit(function() {
    
  pubnub.publish({
    channel: channel,
    message: {
      text: $input.val(),
      username: me
    }
  });
  
  $input.val('');
  
  return false;
  
});

pubnub.subscribe({
  channel: channel,
  message: function(data) {
    
    var $line = $('<li class="list-group-item"><strong>' + data.username + ':</strong> </span>');
    var $message = $('<span class="text" />').text(data.text).html();
    
    $line.append($message);
    $output.append($line);
    
    $output.scrollTop($output[0].scrollHeight);

  }, 
  presence: function(data) {

    console.log(data);

    // get notified when people join
    if(data.action == "join") {

      var $new_user = $('<li id="' + data.uuid + '" class="list-group-item">' + data.uuid + '</li>')

      $('#online-users').append($new_user);

    }

    // and when they leave
    if(data.action == "leave"  || data.action == "timeout") {
      $('#' + data.uuid).remove();
    }

  }
});
</script>

**Comment by zfex77** [comment]
completed task with different approach
